// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:85b6f129-ac6d-437d-9094-09debaebd9cb",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_JVykuzVls",
    "aws_user_pools_web_client_id": "7h1i3jq38bssngtmclgs1h4bea"
};


export default awsmobile;
